# Generated by Django 5.0.7 on 2024-08-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="news",
            name="summary_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="visited_categories",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
