# Generated by Django 5.0.7 on 2024-08-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_news_slug_alter_news_summary_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="alt_content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
