# Generated by Django 5.0.7 on 2024-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_news_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
    ]
