# Generated by Django 5.0.7 on 2024-08-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="newss",
                to="app.category",
            ),
        ),
    ]
