# Generated by Django 5.0.7 on 2024-08-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
