# Generated by Django 5.0.7 on 2024-08-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_comment_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
